### ISSUE TITLE
Allrounder - amazing template

### ISSUE THREAD

**Issue by OleThi** [Bakual/Allrounder#8]
Hello Bakual

Allrounder is a great template - it is obvious that it is made by a designer / artist. 
But it is a shame that it is not responsive, are you  in the process of changing the template so that it will be responsive?
Or do you know if there might any other who is working on this? 

Regards Ole

**Comment by Bakual** [comment]
Closing as the work is now done. See https://github.com/Bakual/Allrounder/releases/tag/2.3.0b2
