### ISSUE TITLE
Fontsize in em doesn't work for editor

### ISSUE THREAD

**Issue by Bakual** [Bakual/Allrounder#9]
When one set a global font size in "em", the editor buttons aren't readable anymore.

**Comment by Minei3oat** [comment]
I cannot confirm this.
Since the editor (which one?) don't uses em in buttons, how could they be not readable?

**Comment by Bakual** [comment]
True enough it's not an issue anymore with TinyMCE since recently the buttons were moved to the top. It still is in JCE and for the "Save"/"Cancel" buttons:
![editor](https://cloud.githubusercontent.com/assets/1018684/18577959/7073b93e-7bed-11e6-989e-f06d1178432c.PNG)
